const PaymentData = {
  gwclPaypoint: [
    {
      id: '1',
      first_name: 'John',
      last_name: 'Doe',
      user_type: 'Vendor',
      reciept_id: '#123343213',
      amount: '$40',
      previous_balance: '$10',
      closing_balance: '-$30',
      recieved_by: {
        first_name: 'Paul',
        last_name: 'Sniff',
        user_type: 'Paypoint Name',
      },
      method: 'Cash',
      payment_date: 'Sept 21, 2020 02:38 PM',
    },
    {
      id: '1',
      first_name: 'John',
      last_name: 'Doe',
      user_type: 'Vendor',
      reciept_id: '#123343213',
      amount: '$40',
      previous_balance: '$10',
      closing_balance: '-$30',
      recieved_by: {
        first_name: 'Paul',
        last_name: 'Sniff',
        user_type: 'Paypoint Name',
      },
      method: 'Cash',
      payment_date: 'Sept 21, 2020 02:38 PM',
    },
    {
      id: '1',
      first_name: 'John',
      last_name: 'Doe',
      user_type: 'Vendor',
      reciept_id: '#123343213',
      amount: '$40',
      previous_balance: '$10',
      closing_balance: '-$30',
      recieved_by: {
        first_name: 'Paul',
        last_name: 'Sniff',
        user_type: 'Paypoint Name',
      },
      method: 'Cash',
      payment_date: 'Sept 21, 2020 02:38 PM',
    },
    {
      id: '1',
      first_name: 'John',
      last_name: 'Doe',
      user_type: 'Vendor',
      reciept_id: '#123343213',
      amount: '$40',
      previous_balance: '$10',
      closing_balance: '-$30',
      recieved_by: {
        first_name: 'Paul',
        last_name: 'Sniff',
        user_type: 'Paypoint Name',
      },
      method: 'Cash',
      payment_date: 'Sept 21, 2020 02:38 PM',
    },
    {
      id: '1',
      first_name: 'John',
      last_name: 'Doe',
      user_type: 'Vendor',
      reciept_id: '#123343213',
      amount: '$40',
      previous_balance: '$10',
      closing_balance: '-$30',
      recieved_by: {
        first_name: 'Paul',
        last_name: 'Sniff',
        user_type: 'Paypoint Name',
      },
      method: 'Cash',
      payment_date: 'Sept 21, 2020 02:38 PM',
    },
  ],
};
export default PaymentData;
