const BillsData = {
  payload: [
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
    {
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
      billed: 10,
      working_meters: 7,
      faulty_meters: 2,
      no_meters: 1,
      exceptions: 1,
      unbilled: 3,
      service_points: 12,
    },
  ],
  meta_data: [
    {
      pagination: {
        total: 7,
        per_page: 15,
        last_page: 1,
        current_page: 1,
        from: 1,
        to: 7,
      },
    },
  ],
};

export default BillsData;
