const NewServiceRequestData = {
  completed: [
    {
      id: 1,
      application_id: 29387364,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      connection_date: 'Jul 24, 2020',
      meter_reader: 'Barima Kwarteng',
      meter_reader_avatar: 'https://bit.ly/3rXu8xK',
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
    },
    {
      id: 2,
      application_id: 29387364,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'what@gmail.com',
      applicant_number: 98410232123,
      connection_date: 'Jul 24, 2020',
      meter_reader: 'Kellie Kotako',
      meter_reader_avatar: 'https://bit.ly/38TOsbP',
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
    },
    {
      id: 3,
      application_id: 29387364,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      connection_date: 'Jul 24, 2020',
      meter_reader: 'Veshraj Joshi',
      meter_reader_avatar: 'https://bit.ly/3rXu8xK',
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
    },
    {
      id: 4,
      application_id: 29387364,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      connection_date: 'Jul 24, 2020',
      meter_reader: 'Barima Kwarteng',
      meter_reader_avatar: 'https://bit.ly/38TOsbP',
      region: 'Region Name',
      district: 'District Name',
      route: 'Route Name',
    },
  ],
  inProgress: [
    {
      id: 1,
      application_id: 2329028,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      request_status: 'Pending',
      request_date: 'Jul 24, 2020',
      address: '311 SS, Harrington St, Raleigh, NC',
    },
    {
      id: 2,
      application_id: 2329028,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'thisisit@gmail.com',
      applicant_number: 98410232123,
      request_status: 'Estimate Sent',
      request_date: 'Jul 24, 2020',
      address: '311 SS, Harrington St, Raleigh, NC',
    },
    {
      id: 3,
      application_id: 2329028,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      request_status: 'Amount Paid',
      request_date: 'Jul 24, 2020',
      address: '311 SS, Harrington St, Raleigh, NC',
    },
    {
      id: 4,
      application_id: 2329028,
      applied_on: 'Jul 24, 2020',
      applicant_name: 'John Doe',
      applicant_mail: 'johndoe@gmail.com',
      applicant_number: 98410232123,
      request_status: 'Pending',
      request_date: 'Jul 24, 2020',
      address: '311 SS, Harrington St, Raleigh, NC',
    },
  ],
};
export default NewServiceRequestData;
