const GeneratedBills = {
  payload: [
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: false,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
    {
      account_name: 'John Doe',
      account_number: '010104174161',
      meter_number: '27364892',
      bill_month: 'December',
      bill_amount: '200',
      delivered_via: 'SMS, Email, Delivery',
      is_working: true,
    },
  ],
  meta_data: [
    {
      pagination: {
        total: 7,
        per_page: 15,
        last_page: 1,
        current_page: 1,
        from: 1,
        to: 7,
      },
    },
  ],
};

export default GeneratedBills;
