const CustomerData = {
  regions: [
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 1,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 2,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
    {
      id: 3,
      region_name: 'Region Name',
      num_of_districts: 24,
      num_of_routes: 12,
    },
  ],
  districts: [
    {
      id: 1,
      district_name: 'District Name',
      region_name: 'Region Name',
      num_of_routes: 12,
    },
    {
      id: 2,
      district_name: 'District Name',
      region_name: 'Region Name',
      num_of_routes: 12,
    },
    {
      id: 3,
      district_name: 'Distric tName',
      region_name: 'Region Name',
      num_of_routes: 12,
    },
  ],
  routes: [
    {
      id: 1,
      route_name: 'Route Name',
      region_name: 'Region Name',
      district_name: 'District Name',
      service_points: 12,
    },
    {
      id: 2,
      route_name: 'Route Name',
      region_name: 'Region Name',
      district_name: 'District Name',
      service_points: 12,
    },
    {
      id: 3,
      route_name: 'Route Name',
      region_name: 'Region Name',
      district_name: 'District Name',
      service_points: 12,
    },
  ],
  servicePoints: [
    {
      id: 1,
      user_name: 'John Doe',
      user_id: '010104174161',
      payment_date: 'Jul 24, 2021',
    },
    {
      id: 1,
      user_name: 'John Doe',
      user_id: '010104174161',
      payment_date: 'Jul 24, 2021',
    },
    {
      id: 1,
      user_name: 'John Doe',
      user_id: '010104174161',
      payment_date: 'Jul 24, 2021',
    },
    {
      id: 1,
      user_name: 'John Doe',
      user_id: '010104174161',
      payment_date: 'Jul 24, 2021',
    },
  ],
  detailData: {
    billing: {
      name: 'Billing Amount',
      amount: '1000',
    },
    receivable: {
      name: 'Total Receivable',
      amount: '12',
    },
    amount_paid: {
      name: 'Amount Paid',
      amount: '800',
    },
    adjustments: {
      name: 'Adjustments',
      amount: '12',
    },
  },
  payload: [
    {
      id: 1,
      account_name: 'Farhan Bowes',
      account_number: '821022',
      customer_status: 'active',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 2,
      account_name: 'Aj Perry',
      account_number: '686922',
      customer_status: 'disconnected',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 3,
      account_name: 'Fahima Paine',
      account_number: '296411',
      customer_status: 'active',
      meter_status: 'faulty',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 4,
      account_name: 'Cheryl Shelton',
      account_number: '752465',
      customer_status: 'active',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 5,
      account_name: 'Jon Davidson',
      account_number: '675816',
      customer_status: 'active',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 6,
      account_name: 'Leonardo Warner',
      account_number: '164683',
      customer_status: 'active',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 7,
      account_name: 'Jason Cowan',
      account_number: '956330',
      customer_status: 'active',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 8,
      account_name: 'Marta Rankin',
      account_number: '652582',
      customer_status: 'disconnected',
      meter_status: 'working',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 9,
      account_name: 'Alberto Leal',
      account_number: '618928',
      customer_status: 'active',
      meter_status: 'faulty',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
    {
      id: 10,
      account_name: 'Annabelle Haworth',
      account_number: '284758',
      customer_status: 'disconnected',
      meter_status: 'faulty',
      meter_type: 'mechanical',
      last_payment_on: '2020-06-24',
    },
  ],
  meta_data: [
    {
      pagination: {
        total: 7,
        per_page: 15,
        last_page: 1,
        current_page: 1,
        from: 1,
        to: 7,
      },
    },
  ],
};

export default CustomerData;
